### ISSUE TITLE
Spec passes nil for *testing.T

### ISSUE THREAD

**Issue by arsham** [sclevine/spec#11]
Hi,

Spec calls the passed function `x+1` times per `it` calls, and the first time it passes `nil` for `t`. For instance snippet:
```go
func TestSpec(t *testing.T) {
	spec.Run(t, "foo", func(t *testing.T, when spec.G, it spec.S) {
		fmt.Println(t == nil)
		it("bar", func() {})
	}, spec.Report(report.Terminal{}))
}
```
Prints `true` then `false`.

Thank you.

Go version: go1.12.7 linux/amd64 (modules enabled)
Spec version: v1.2.0 (b518b20aa)

**Comment by sclevine** [comment]
This is intentional -- everything outside of the `it` block needs to be executed an additional time during the parse phase so that each test execution gets fresh closures (to prevent test pollution).

You should only use `t` inside of an `it` block, where the `t` provided will be the correct subtest-scoped `t`, and not the global `t` passed to `TestSpec`.

`t` is set to `nil` in the case you mention because:
1. The parse phase runs once for all `it`s, so we can't pass a subtest-scoped version of it.
2. Using `t` outside of `it` should panic so that you know you've made a mistake.

Try:
```go
func TestSpec(t *testing.T) {
	spec.Run(t, "foo", func(t *testing.T, when spec.G, it spec.S) {
		it.Before("before each it", func() {
			fmt.Println(t == nil)
		})

		it("for each it", func() {
			fmt.Println(t == nil)
		})
	}, spec.Report(report.Terminal{}))
}
```

**Comment by arsham** [comment]
Makes sense, thank you for clarifying.
