### ISSUE TITLE
Question: Can this be better organized?

### ISSUE THREAD

**Issue by zachgersh** [sclevine/spec#15]
We've been happily using spec on `doctl` but I am a little sad about how things are organized right now (my own doing):

https://github.com/digitalocean/doctl/tree/master/integration

We've original had the suite registration pattern but switched to this pattern 
```go
func TestAccounts(t *testing.T) {
	spec.Run(t, "account/get", testAccountGet, spec.Report(report.Terminal{}))
	spec.Run(t, "account/ratelimit", testAccountRateLimit, spec.Report(report.Terminal{}))
}
```

It looks more "go like" and people don't forget to go to the `init_test.go` and register their suite.

BUT

Now on failure I have every suite reporting with a separate passed output like this example:
```bash
Suite: compute/droplet/actions
Total: 1 | Focused: 0 | Pending: 0
.
Passed: 1 | Failed: 0 | Skipped: 0

Suite: compute/droplet/backups
Total: 1 | Focused: 0 | Pending: 0
.
Passed: 1 | Failed: 0 | Skipped: 0

Suite: compute/droplet/create
Total: 7 | Focused: 0 | Pending: 0
.......
Passed: 7 | Failed: 0 | Skipped: 0

Suite: compute/droplet/delete
Total: 4 | Focused: 0 | Pending: 0
....
Passed: 4 | Failed: 0 | Skipped: 0
```

I really would love to organize with the current pattern but keep the compact pattern of reporter for the entire suite. Unsure of a good way to do that though. Thoughts?

**Comment by sclevine** [comment]
You could use a `spec.Suite` without making it global:
```go
func TestAccounts(t *testing.T) {
	suite := spec.New("account", spec.Report(report.Terminal{}))
	suite("get", testAccountGet)
	suite("ratelimit", testAccountRateLimit)
	suite.Run(t)
}
```
This is no less "go like" than `spec.S` or `spec.G`, which are also function types.

Alternatively, you could use a top-level `spec.G`:
```go
func TestAccounts(t *testing.T) {
	spec.Run(t, "account", func(t *testing.T, when spec.G, it spec.S) {
		when("get", func() { testAccountGet(t, when, it) })
		when("ratelimit", func() { testAccountRateLimit(t, when, it) })
	}, spec.Report(report.Terminal{}))
}
```

That said, the real issue here is reporting. I added the reporter interface before `go test -json` was available. Now that `go test` can provide machine-readable test output, reporting should probably be out-of-scope for spec. Here's a popular alternative that looks much nicer compared to the example reporters: https://github.com/gotestyourself/gotestsum

(I should probably add that to the README at some point.)

**Comment by zachgersh** [comment]
@sclevine - I like `gotestsum` need to investigate that some more. I had the original suite registration you have above BUT we are using a test main (building a binary to run the tests against and setting up some temp dirs) and people would inevitably forget to go register their test in Main and then everything would be green.

So using the `spec.Run` declared near the unexported test function helps people remember but then I get the output of all of this tests treated as different suites.

Does that make sense?

**Comment by sclevine** [comment]
That the output is organized into suites is entirely because the `report.Terminal` reporter displays it that way. If you don’t want to use gotestsum to report all the subtests in a package together, maybe you could create a custom `spec.Reporter` that’s shared between `spec.Run` calls and is manually summarized in your `TestMain`? That would allow you to define multiple `TestX` functions without multiple suites.

Alternatively, you could define a global `suite`, a single `TestX` function with a `suite.Run(t)`, and make `suite` calls in the global scope. See: https://github.com/sclevine/spec/pull/2

**Comment by zachgersh** [comment]
Thanks @sclevine - I went ahead and went with #2 and the `var _ =` approach. Seemed to fit exactly what I was trying to do.
