### ISSUE TITLE
Add support for BeforeAll and AfterAll

### ISSUE THREAD

**Issue by djoyahoy** [sclevine/spec#7]

**Comment by sclevine** [comment]
These constructs are intentionally not supported because setup/teardown code can go before/after `spec.Run` or `suite.Run`.

Additionally, introducing BeforeAll and AfterAll closures inside of `when` blocks that are shared between `it` blocks would lead to race conditions when tests are run in parallel.

**Comment by dmikusa-pivotal** [comment]
Is there an example of how this would look?

Is this what you're saying?

```
func TestUnitContributor(t *testing.T) {
    // do BeforeAll here
    spec.Run(t, "Contributor", testContributor, spec.Report(report.Terminal{}))
   // do AfterAll here?
}
```

**Comment by sclevine** [comment]
Yep, you could even inline `testContributor` if you need access to the BeforeAll/AfterAll closure.
