### ISSUE TITLE
Summary report

### ISSUE THREAD

**Issue by joaopapereira** [sclevine/spec#9]
It would help if in the end of the tests we got a summary of the tests that failed.

This feature would help when the system under tests have a big number of packages and tests, because the errors could be in the beginning of the output and there is no visual information that a test failed.

**Comment by sclevine** [comment]
The worst aspect of this UX (not noticing that any tests failed) should be covered by this: https://github.com/golang/go/issues/30507

Locally, I often run with `go test` instead of `go test -v` so that I only see test failures. I also direct stdout/stderr from my code to `it.Out()` which only appears on test failure (using the included reporters). But I understand that this doesn't cover the CI use case, where you want to see all the tests and a summary.

I don't think this feature would be a good fit for spec, given that it just organizes subtests and doesn't operate across packages. However, this could be implemented as a CLI tool that parses `go test -json` (introduced in Go 1.10). In fact, [it has](https://github.com/gotestyourself/gotestsum), and that CLI is available on a number of CI platforms (like CircleCI). 😄 

I've actually considered deprecating the reporter interface entirely, but I think it's nice to have an option that works without installing an additional CLI.

**Comment by marco-m** [comment]
FYI, golang/go#30507 has been closed with a commit to master a few days ago.

**Comment by kardolus** [comment]
@joaopapereira I have been parsing the output of spec to `tee >(richgo testfilter)` - richgo gives you colors and all. --> https://github.com/kyoh86/richgo

**Comment by sclevine** [comment]
Closing given the available options.
